version: "3"
services:
  webapp.api:
    build: WebApp.Api/.
    image: tomato/webapp/api:latest
    ports:
      - "5050:80"
      - "5051:443"
  auth0.api:
    build: Auth0.Api/.
    image: tomato/auth0/api:latest
    ports:
      - "5060:80"
      - "5061:443"
  vendor.api:
    build: Vendor.Api/.
    image: tomato/vendor/api:latest
    ports:
      - "5070:80"
      - "5071:443"