version: '3.4'

services:
  webapp.api:
    image: ${DOCKER_REGISTRY-}webappapi:${TAG}
    container_name: WebApp.Api
    
    build:
      context: ./WebApp.Api
      dockerfile: WebApp.Api/Dockerfile
      labels:
        - "com.microsoft.visual-studio.project-name=WebApp.Api"