version: "3.7"
services:
  webapp.api:
    image: webappapi:dev
    
    build:
      dockerfile: ./WebApp.Api/Dockerfile
      context: ./WebApp.Api

    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: 5051

    ports:
    - "5050:80"
    - "5051:443"

    entrypoint: tail webappapi:dev -f /dev/null