version: '3.4'

services:
  webapp.api:
    image: ${DOCKER_REGISTRY-}webappapi:${TAG}
    container_name: WebApp.Api
    
    build:
      context: ./WebApp.Api
      dockerfile: Dockerfile
      labels:
        - "com.microsoft.visual-studio.project-name=WebApp.Api"
        
    depends_on:
      - auth0.api
      - vendor.api
  
  auth0.api:
    image: ${DOCKER_REGISTRY-}auth0api:${TAG}
    container_name: Auth0.Api
    
    build:
      context: ./Auth0.Api
      dockerfile: Dockerfile
      labels:
        - "com.microsoft.visual-studio.project-name=Auth0.Api"

  vendor.api:
    image: ${DOCKER_REGISTRY-}vendorapi:${TAG}
    container_name: Vendor.Api
    
    build:
      context: ./Vendor.Api
      dockerfile: Dockerfile
      labels:
        - "com.microsoft.visual-studio.project-name=Vendor.Api"