export const ABOUT_FAILURE = 'about/FAILURE';
export const ABOUT_SUCCESS = 'about/SUCCESS';
export const ABOUT_API_PROPERTIES_CLEAR = 'about/API_PROPERTIES_CLEAR';
export const ABOUT_API_PROPERTIES_IS_FETCHING = 'about/API_PROPERTIES_IS_FETCHING';
